# GroupBy

### Introduction:

GroupBy can be summarized as Split-Apply-Combine.

Special thanks to: https://github.com/justmarkham for sharing the dataset and materials.

Check out this [Diagram](http://i.imgur.com/yjNkiwL.png)  
### Step 1. Import the necessary libraries

In [10]:
import pandas as pd
pd.set_option('display.max_rows', 500)

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/drinks.csv).

In [11]:
pd.read_csv("https://raw.githubusercontent.com/justmarkham/DAT8/master/data/drinks.csv")

,country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,continent
0,Afghanistan,0,0,0,0.0,AS
1,Albania,89,132,54,4.9,EU
2,Algeria,25,0,14,0.7,AF
3,Andorra,245,138,312,12.4,EU
4,Angola,217,57,45,5.9,AF
5,Antigua & Barbuda,102,128,45,4.9,NaN
6,Argentina,193,25,221,8.3,SA
7,Armenia,21,179,11,3.8,EU
8,Australia,261,72,212,10.4,OC
9,Austria,279,75,191,9.7,EU
10,Azerbaijan,21,46,5,1.3,EU
11,Bahamas,122,176,51,6.3,NaN
12,Bahrain,42,63,7,2.0,AS
13,Bangladesh,0,0,0,0.0,AS
14,Barbados,143,173,36,6.3,NaN
15,Belarus,142,373,42,14.4,EU
16,Belgium,295,84,212,10.5,EU
17,Belize,263,114,8,6.8,NaN
18,Benin,34,4,13,1.1,AF
19,Bhutan,23,0,0,0.4,AS
20,Bolivia,167,41,8,3.8,SA
21,Bosnia-Herzegovina,76,173,8,4.6,EU
22,Botswana,173,35,35,5.4,AF
23,Brazil,245,145,16,7.2,SA
24,Brunei,31,2,1,0.6,AS
25,Bulgaria,231,252,94,10.3,EU
26,Burkina Faso,25,7,7,4.3,AF
27,Burundi,88,0,0,6.3,AF
28,Cote d'Ivoire,37,1,7,4.0,AF
29,Cabo Verde,144,56,16,4.0,AF
30,Cambodia,57,65,1,2.2,AS
31,Cameroon,147,1,4,5.8,AF
32,Canada,240,122,100,8.2,NaN
33,Central African Republic,17,2,1,1.8,AF
34,Chad,15,1,1,0.4,AF
35,Chile,130,124,172,7.6,SA
36,China,79,192,8,5.0,AS
37,Colombia,159,76,3,4.2,SA
38,Comoros,1,3,1,0.1,AF
39,Congo,76,1,9,1.7,AF
40,Cook Islands,0,254,74,5.9,OC
41,Costa Rica,149,87,11,4.4,NaN
42,Croatia,230,87,254,10.2,EU
43,Cuba,93,137,5,4.2,NaN
44,Cyprus,192,154,113,8.2,EU
45,Czech Republic,361,170,134,11.8,EU
46,North Korea,0,0,0,0.0,AS
47,DR Congo,32,3,1,2.3,AF
48,Denmark,224,81,278,10.4,EU
49,Djibouti,15,44,3,1.1,AF
50,Dominica,52,286,26,6.6,NaN
51,Dominican Republic,193,147,9,6.2,NaN
52,Ecuador,162,74,3,4.2,SA
53,Egypt,6,4,1,0.2,AF
54,El Salvador,52,69,2,2.2,NaN
55,Equatorial Guinea,92,0,233,5.8,AF
56,Eritrea,18,0,0,0.5,AF
57,Estonia,224,194,59,9.5,EU
58,Ethiopia,20,3,0,0.7,AF
59,Fiji,77,35,1,2.0,OC
60,Finland,263,133,97,10.0,EU
61,France,127,151,370,11.8,EU
62,Gabon,347,98,59,8.9,AF
63,Gambia,8,0,1,2.4,AF
64,Georgia,52,100,149,5.4,EU
65,Germany,346,117,175,11.3,EU
66,Ghana,31,3,10,1.8,AF
67,Greece,133,112,218,8.3,EU
68,Grenada,199,438,28,11.9,NaN
69,Guatemala,53,69,2,2.2,NaN
70,Guinea,9,0,2,0.2,AF
71,Guinea-Bissau,28,31,21,2.5,AF
72,Guyana,93,302,1,7.1,SA
73,Haiti,1,326,1,5.9,NaN
74,Honduras,69,98,2,3.0,NaN
75,Hungary,234,215,185,11.3,EU
76,Iceland,233,61,78,6.6,EU
77,India,9,114,0,2.2,AS
78,Indonesia,5,1,0,0.1,AS
79,Iran,0,0,0,0.0,AS
80,Iraq,9,3,0,0.2,AS
81,Ireland,313,118,165,11.4,EU
82,Israel,63,69,9,2.5,AS
83,Italy,85,42,237,6.5,EU
84,Jamaica,82,97,9,3.4,NaN
85,Japan,77,202,16,7.0,AS
86,Jordan,6,21,1,0.5,AS
87,Kazakhstan,124,246,12,6.8,AS
88,Kenya,58,22,2,1.8,AF
89,Kiribati,21,34,1,1.0,OC
90,Kuwait,0,0,0,0.0,AS
91,Kyrgyzstan,31,97,6,2.4,AS
92,Laos,62,0,123,6.2,AS
93,Latvia,281,216,62,10.5,EU
94,Lebanon,20,55,31,1.9,AS
95,Lesotho,82,29,0,2.8,AF
96,Liberia,19,152,2,3.1,AF
97,Libya,0,0,0,0.0,AF
98,Lithuania,343,244,56,12.9,EU
99,Luxembourg,236,133,271,11.4,EU
100,Madagascar,26,15,4,0.8,AF
101,Malawi,8,11,1,1.5,AF
102,Malaysia,13,4,0,0.3,AS
103,Maldives,0,0,0,0.0,AS
104,Mali,5,1,1,0.6,AF
105,Malta,149,100,120,6.6,EU
106,Marshall Islands,0,0,0,0.0,OC
107,Mauritania,0,0,0,0.0,AF
108,Mauritius,98,31,18,2.6,AF
109,Mexico,238,68,5,5.5,NaN
110,Micronesia,62,50,18,2.3,OC
111,Monaco,0,0,0,0.0,EU
112,Mongolia,77,189,8,4.9,AS
113,Montenegro,31,114,128,4.9,EU
114,Morocco,12,6,10,0.5,AF
115,Mozambique,47,18,5,1.3,AF
116,Myanmar,5,1,0,0.1,AS
117,Namibia,376,3,1,6.8,AF
118,Nauru,49,0,8,1.0,OC
119,Nepal,5,6,0,0.2,AS
120,Netherlands,251,88,190,9.4,EU
121,New Zealand,203,79,175,9.3,OC
122,Nicaragua,78,118,1,3.5,NaN
123,Niger,3,2,1,0.1,AF
124,Nigeria,42,5,2,9.1,AF
125,Niue,188,200,7,7.0,OC
126,Norway,169,71,129,6.7,EU
127,Oman,22,16,1,0.7,AS
128,Pakistan,0,0,0,0.0,AS
129,Palau,306,63,23,6.9,OC
130,Panama,285,104,18,7.2,NaN
131,Papua New Guinea,44,39,1,1.5,OC
132,Paraguay,213,117,74,7.3,SA
133,Peru,163,160,21,6.1,SA
134,Philippines,71,186,1,4.6,AS
135,Poland,343,215,56,10.9,EU
136,Portugal,194,67,339,11.0,EU
137,Qatar,1,42,7,0.9,AS
138,South Korea,140,16,9,9.8,AS
139,Moldova,109,226,18,6.3,EU
140,Romania,297,122,167,10.4,EU
141,Russian Federation,247,326,73,11.5,AS
142,Rwanda,43,2,0,6.8,AF
143,St. Kitts & Nevis,194,205,32,7.7,NaN
144,St. Lucia,171,315,71,10.1,NaN
145,St. Vincent & the Grenadines,120,221,11,6.3,NaN
146,Samoa,105,18,24,2.6,OC
147,San Marino,0,0,0,0.0,EU
148,Sao Tome & Principe,56,38,140,4.2,AF
149,Saudi Arabia,0,5,0,0.1,AS
150,Senegal,9,1,7,0.3,AF
151,Serbia,283,131,127,9.6,EU
152,Seychelles,157,25,51,4.1,AF
153,Sierra Leone,25,3,2,6.7,AF
154,Singapore,60,12,11,1.5,AS
155,Slovakia,196,293,116,11.4,EU
156,Slovenia,270,51,276,10.6,EU
157,Solomon Islands,56,11,1,1.2,OC
158,Somalia,0,0,0,0.0,AF
159,South Africa,225,76,81,8.2,AF
160,Spain,284,157,112,10.0,EU
161,Sri Lanka,16,104,0,2.2,AS
162,Sudan,8,13,0,1.7,AF
163,Suriname,128,178,7,5.6,SA
164,Swaziland,90,2,2,4.7,AF
165,Sweden,152,60,186,7.2,EU
166,Switzerland,185,100,280,10.2,EU
167,Syria,5,35,16,1.0,AS
168,Tajikistan,2,15,0,0.3,AS
169,Thailand,99,258,1,6.4,AS
170,Macedonia,106,27,86,3.9,EU
171,Timor-Leste,1,1,4,0.1,AS
172,Togo,36,2,19,1.3,AF
173,Tonga,36,21,5,1.1,OC
174,Trinidad & Tobago,197,156,7,6.4,NaN
175,Tunisia,51,3,20,1.3,AF
176,Turkey,51,22,7,1.4,AS
177,Turkmenistan,19,71,32,2.2,AS
178,Tuvalu,6,41,9,1.0,OC
179,Uganda,45,9,0,8.3,AF
180,Ukraine,206,237,45,8.9,EU
181,United Arab Emirates,16,135,5,2.8,AS
182,United Kingdom,219,126,195,10.4,EU
183,Tanzania,36,6,1,5.7,AF
184,USA,249,158,84,8.7,NaN
185,Uruguay,115,35,220,6.6,SA
186,Uzbekistan,25,101,8,2.4,AS
187,Vanuatu,21,18,11,0.9,OC
188,Venezuela,333,100,3,7.7,SA
189,Vietnam,111,2,1,2.0,AS
190,Yemen,6,0,0,0.1,AS
191,Zambia,32,19,4,2.5,AF
192,Zimbabwe,64,18,4,4.7,AF

### Step 3. Assign it to a variable called drinks and look at the first 10 rows of the DF.

In [3]:
drinks = pd.read_csv('https://raw.githubusercontent.com/justmarkham/DAT8/master/data/drinks.csv')

drinks.head(10)

,country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,continent
0,Afghanistan,0,0,0,0.0,AS
1,Albania,89,132,54,4.9,EU
2,Algeria,25,0,14,0.7,AF
3,Andorra,245,138,312,12.4,EU
4,Angola,217,57,45,5.9,AF
5,Antigua & Barbuda,102,128,45,4.9,NaN
6,Argentina,193,25,221,8.3,SA
7,Armenia,21,179,11,3.8,EU
8,Australia,261,72,212,10.4,OC
9,Austria,279,75,191,9.7,EU

### Step 4. Which continent drinks more beer on average?

In [7]:
drinks.groupby('continent')['beer_servings'].mean()

continent
AF     61.471698
AS     37.045455
EU    193.777778
OC     89.687500
SA    175.083333
Name: beer_servings, dtype: float64

### Step 5. For each continent print the summary statistics for wine consumption.

In [8]:
drinks.groupby('continent')['wine_servings'].describe()

           count        mean        std  min   25%    50%     75%    max
continent
AF          53.0   16.264151  38.846419  0.0   1.0    2.0   13.00  233.0
AS          44.0    9.068182  21.667034  0.0   0.0    1.0    8.00  123.0
EU          45.0  142.222222  97.421738  0.0  59.0  128.0  195.00  370.0
OC          16.0   35.625000  64.555790  0.0   1.0    8.5   23.25  212.0
SA          12.0   62.416667  88.620189  1.0   3.0   12.0   98.50  221.0

### Step 6. Print the mean alcoohol consumption per continent for every column

In [13]:
drinks.groupby('continent').mean()

,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol
continent,,,,
AF,61.471698,16.339623,16.264151,3.007547
AS,37.045455,60.840909,9.068182,2.170455
EU,193.777778,132.555556,142.222222,8.617778
OC,89.687500,58.437500,35.625000,3.381250
SA,175.083333,114.750000,62.416667,6.308333

### Step 7. Print the median alcoohol consumption per continent for every column

In [14]:
drinks.groupby('continent').median()

,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol
continent,,,,
AF,32.0,3.0,2.0,2.30
AS,17.5,16.0,1.0,1.20
EU,219.0,122.0,128.0,10.00
OC,52.5,37.0,8.5,1.75
SA,162.5,108.5,12.0,6.85

### Step 8. Print the mean, min and max values for spirit consumption.

In [15]:
drinks.groupby('continent')['spirit_servings'].aggregate(['mean','max','min'])

                 mean  max  min
continent
AF          16.339623  152    0
AS          60.840909  326    0
EU         132.555556  373    0
OC          58.437500  254    0
SA         114.750000  302   25

### Step 9. Print the mean, min and max values for beer consumption and the mean and std deviation for wine consumption.

In [16]:
import numpy as np

In [19]:
drinks.groupby('continent').agg({'beer_servings':['mean','max','min'],'wine_servings':['mean', 'std']})

          beer_servings          wine_servings
                   mean  max min          mean        std
continent
AF            61.471698  376   0     16.264151  38.846419
AS            37.045455  247   0      9.068182  21.667034
EU           193.777778  361   0    142.222222  97.421738
OC            89.687500  306   0     35.625000  64.555790
SA           175.083333  333  93     62.416667  88.620189

### Step 10.  Create a custom aggregation function and apply it to some of the columns